-- Tunables for the discrete LQI regulator (aircraft/lqi.lua). The gain matrix K
-- and plant metadata come from aircraft/plant_K.lua (generated by
-- model/build_plant.py). Override via /aircraft/user_config.lua-style file if
-- desired, but this file is the single place for LQI runtime knobs.
return {
    dt = 0.05,

    -- Hover feedforward: the main-lift command that holds the craft. Captured
    -- live at engage (bumpless), this is only the fallback / initial value. The
    -- LQI integral trims any residual, so it need not be exact.
    uNominal = { mainLift = 120, forwardBack = 0, leftRight = 0, yaw = 0, upDown = 0 },

    -- Actuator first-order time constants (s), used to propagate the
    -- command-equivalent actuator states. MUST match the model build.
    tau = { mainLift = 0.59, forwardBack = 0.51, leftRight = 0.32, yaw = 0.32, upDown = 0.44 },

    -- Per-channel command clamps (RSC target speed units).
    limit = {
        mainLift    = { 0, 256 },
        forwardBack = { -256, 256 },
        leftRight   = { -256, 256 },
        yaw         = { -256, 256 },
        upDown      = { -256, 256 },
    },

    -- Yaw rate source: gimbal getAngularRatesRad index (Lua 1-based) about +y.
    -- Pulse data (2026/08/20) showed yaw responds on index 2 (middle element).
    yawRateIndex = 2,
    yawRateSign = 1,

    -- World->body rotation (deg) applied to the horizontal POSITION error only
    -- (velocity is already body-frame from the sensors). Tune if position hold
    -- rotates/spirals. Only used when enable.position = true.
    headingOffsetDeg = 0,

    -- Integral anti-windup clamps per tracked output (deviation-seconds).
    xiMax = { s_x = 50, s_y = 50, s_z = 50, psi = 5 },

    -- Subsystem gates for the OUTER setpoint holds. Inner damping (velocity, yaw
    -- rate, actuator states) is always active. Recommended bring-up order:
    -- 1) position=false, heading=false  -> altitude hold + drift/rate damping
    -- 2) heading=true                   -> add heading hold
    -- 3) position=true                  -> add absolute X/Z hold (needs headingOffsetDeg)
    enable = { altitude = true, heading = false, position = false },

    keys = { engage = keys.p, override = keys.o },
}
